// <auto-generated />
namespace CinemaTickets.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sessionfilmhallrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sessionfilmhallrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201705190711167_session-film-hall-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
