// <auto-generated />
namespace CinemaTickets.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class filmaddrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(filmaddrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201705191344507_film-add-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
